create database epicGameShop1

drop database epicGameShop1


use epicGameShop1


-- User Table
CREATE TABLE Users (
    UserID INT PRIMARY KEY IDENTITY,
    Username NVARCHAR(60) UNIQUE,
    Password NVARCHAR(100), -- Hashed and salted for security
    Role INT, -- 1 is productManager 2 is user
    DateCreated NVARCHAR(50),
    UserPurse DECIMAL(10, 2)
);

-- Genres Table
CREATE TABLE Genres (
    GenreID INT PRIMARY KEY IDENTITY,
    GenreName NVARCHAR(200) UNIQUE
);

-- Games Table
CREATE TABLE Games (
    GameID INT PRIMARY KEY IDENTITY,
    Title NVARCHAR(400),
    Description NVARCHAR(MAX),
    GenreID INT,
	ImageLink NVARCHAR(MAX),
    Developer NVARCHAR(100),
    ReleaseDate NVARCHAR(60),
    Price DECIMAL(10, 2),
	FOREIGN KEY (GenreID) REFERENCES Genres(GenreID)
);


-- User Games Library Table (Many-to-Many Relationship)
CREATE TABLE UserGamesLibrary (
    UserID INT,
    GameID INT,
    PRIMARY KEY (UserID, GameID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (GameID) REFERENCES Games(GameID)
);

-- User Transactions History Table
CREATE TABLE UserTransactions (
    TransactionID INT PRIMARY KEY IDENTITY,
    UserID INT,
    BoughtedGames NVARCHAR(MAX),
    TransactionDate NVARCHAR(50),
    PaymentMethod NVARCHAR(50),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

-- User Transactions Details Table (for storing individual bought games per transaction)
CREATE TABLE UserTransactionDetails (
    TransactionDetailID INT PRIMARY KEY IDENTITY,
    TransactionID INT,
    GameID INT,
    FOREIGN KEY (TransactionID) REFERENCES UserTransactions(TransactionID),
    FOREIGN KEY (GameID) REFERENCES Games(GameID)
);





SELECT Games.*
FROM Games
INNER JOIN UserGamesLibrary ON Games.GameID = UserGamesLibrary.GameID
WHERE UserGamesLibrary.UserID = 1;



select * from Games 
where GameID = ?









SELECT G.*, Genres.GenreName
FROM Games AS G
INNER JOIN Genres ON G.GenreID = Genres.GenreID
where G.GameID = 56




-- Insert data into Genres table
INSERT INTO Genres (GenreName) VALUES ('Action');
INSERT INTO Genres (GenreName) VALUES ('Adventure');
INSERT INTO Genres (GenreName) VALUES ('RPG');
INSERT INTO Genres (GenreName) VALUES ('Shooter');
INSERT INTO Genres (GenreName) VALUES ('Racing');
INSERT INTO Genres (GenreName) VALUES ('Sports');







-- Insert data into Games table with ImageLinks
INSERT INTO Games (Title, Description, GenreID, ImageLink, Developer, ReleaseDate, Price) VALUES
('HELLDIVERS 2', 'Helldivers 2 is a 2024 cooperative third-person shooter game developed by Arrowhead Game Studios and published by Sony Interactive Entertainment. Helldivers 2 is set a century after the triumph of "Super Earth", a self-described managed democracy, over the Cyborgs, Terminids, and Illuminate during the events of the first game. It is discovered that, upon death, the Terminids produce a unique and highly valuable resource known as E-710. Farms are established on human-colonized worlds, but containment is eventually breached, releasing the bugs and causing chaos and destruction. Simultaneously, a new threat emerges in the form of the Automatons, a mechanical army intent on destroying humanity. ', 1, 'helldivers-2', 'Arrowhead Game Studios', '2023-08-25', 59.99),
('Starfield', 'Starfield is an action role-playing video game. The player can switch between a first-person and third-person perspective at any time. The game features an open world in the form of an area within the Milky Way galaxy, containing both fictional and non-fictional planetary systems. The player is able to land on more than 1,000 planets and an unspecified number of moons and space stations. The majority of the landscapes within the game were procedurally generated, depending on the star of its system and its atmosphere, as well as locations of interest as the player approaches a planet, with modified and handcrafted content developed around them. The largest city in the game, New Atlantis, is the largest fictional city Bethesda has developed. As the player explores the game world, they encounter various non-playable characters (NPCs), some of whom have the option to join the players crew. Such NPCs may aid the player in combat, carry items, speak to other NPCs on the players behalf during confrontations, and comment on choices the player makes. The player may station crew members at any of their constructed outposts. Each companion character has their own unique skills and abilities. Some recruitable NPCs can be romanced by the player.', 3, 'starfield', 'Bethesda Game Studios', '2023-09-06', 69.99),
('The Last of Us Part II', 'The Last of Us Part II is a 2020 action-adventure game developed by Naughty Dog and published by Sony Interactive Entertainment. Set five years after The Last of Us (2013), the game focuses on two playable characters in a post-apocalyptic United States whose lives intertwine: Ellie, who sets out in revenge for a murder, and Abby, a soldier who becomes involved in a conflict between her militia and a religious cult. The game uses a third-person perspective; the player must fight human enemies and cannibalistic zombie-like creatures with firearms, improvised weapons, and stealth.', 2, 'the-last-of-us-part-II', 'Naughty Dog', '2020-06-19', 59.99),
('Hogwarts Legacy', 'Hogwarts Legacy is a 2023 action role-playing game developed by Avalanche Software and published by Warner Bros. Games under its Portkey Games label. The game is part of the Wizarding World franchise, taking place a century prior to the events chronicled in the Harry Potter novels. The player controls a student enrolled in the Hogwarts School of Witchcraft and Wizardry who learns to wield an array of magical abilities and objects. With the assistance of fellow students and professors, the protagonist embarks on a journey to unearth an ancient secret concealed within the wizarding world.', 3, 'hogwarts-legacy', 'Portkey Games', '2023-02-10', 59.99),
('Atomic Heart', 'Atomic Heart is a first-person shooter video game with role-playing elements. The combat consists of shooting and slashing with improvised weapons. A wide variety of enemies are featured, which may be mechanical, biomechanical, biological, and some of which are airborne. A crafting system allows the player to piece weapons together from metal parts that can be detached from robots or taken from household appliances. Weapons can be upgraded via a mechanic called "cassettes". Ammo in the game is scarce, and there is a stealth option. Quick-time events are featured in the game. The player wears a special glove, the Polymer Glove, which grants powers such as telekinesis, freezing, and electricity to defeat foes. Its powers can be combined with both melee and ranged weapons.

Ammunition can be upgraded with various elemental effects using "canisters". These canisters can be looted and crafted, and equipped by the player on both melee and ranged weapons. If the canister depletes, it is discarded from the players inventory.', 3, 'Atomic-Heart', 'Mundfish', '2023-03-20', 59.99),
('Monster Hunter Rise', 'Monster Hunter Rise is a 2021 action role-playing game developed and published by Capcom for the Nintendo Switch. It is the sixth main installment in the Monster Hunter series. It was released worldwide in March 2021, with a Windows port released in January 2022 and ports for PlayStation 4, PlayStation 5, Xbox One, and Xbox Series X/S were released in January 2023. An expansion pack, Sunbreak, was released in June 2022. As with previous Monster Hunter titles, Monster Hunter Rise has the player take the role of a Hunter, tasked with slaying or capturing large monsters using a variety of weapons, tools, and environmental features to damage and weaken them while surviving their attacks. Successful completion of the offered quests provides loot, typically in the form of various monster parts from the monster, which are used to forge new armor and weapons that can be used to take on more powerful monsters, forming the series notable core loop. Several of the series monsters return along with a host of new monsters developed for Rise. All fourteen weapon types that have been present in both Monster Hunter Generations and World, which mix archetypes of swords, shields, staves, bows, and guns, are present in Rise.', 1, 'monsterhunterrise', 'Capcom', '2021-03-26', 59.99),
('Resident Evil 8 Village', 'Resident Evil Village is a 2021 survival horror game developed and published by Capcom. It is the sequel to Resident Evil 7: Biohazard (2017) and the tenth main game of the Resident Evil series. Players control Ethan Winters, who searches for his kidnapped daughter in a village filled with mutant creatures. Village maintains survival horror elements from previous games, with players scavenging environments for items and managing resources while adding more action-oriented gameplay, with higher enemy counts and a greater emphasis on combat. Like its predecessor, Resident Evil 7: Biohazard, Resident Evil Village uses a first-person perspective, and has the option for a third-person perspective. It is set in a snowy explorable European village, described as pulled straight from the Victorian era and much larger and more immersive than its predecessor. Structures and buildings in the central village can be climbed and used to fight enemies. Compared to Biohazard, the game is more action-focused, with protagonist Ethan Winters equipped with more combat skills due to military training. The games primary enemies, the werewolf-like Lycans, are agile and intelligent and can wield weapons and attack in packs, forcing the player to rethink their strategy on whether to use sparse ammunition, use melee combat, or run away. Similar to Resident Evil 4 (2005), makeshift barricades can be used to fend off enemies.', 1, 'Re8', 'Capcom', '2021-05-07', 59.99),
('Mortal Kombat 11', 'Mortal Kombat 11 is a 2019 fighting game developed by NetherRealm Studios and published by Warner Bros. Interactive Entertainment. It is the eleventh main installment in the Mortal Kombat series and a sequel to Mortal Kombat X (2015). The game was announced at The Game Awards 2018 and was released in North America and Europe on April 23, 2019, for Nintendo Switch, PlayStation 4, Windows, and Xbox One—with the exception of Europes Switch version which was released on May 10, 2019. It was released on Stadia on November 19, 2019. Like the previous three games in the series, including Mortal Kombat Mobile, Mortal Kombat 11 is a 2.5D fighting game. Alongside the returning Fatalities, Brutalities, Stage Fatalities, Friendships and Quitalities, new gameplay features are introduced, such as Fatal Blows and Krushing Blows. Fatal Blows are special moves similar to the X-ray moves in the 2011 reboot and Mortal Kombat X. Like X-ray moves, Fatal Blows deal a large amount of damage, but unlike them, they only become available when a players health drops below 30%, and can only be performed once per match. Krushing Blows are a critical hit variation of a given special move or combination, triggered when certain requirements are met and cause deadly effect by showing graphic body injuries and draining at most times 30% health in a single hit. New to the series is a Flawless Block mechanic, which allows for a comeback window after blocking an attack with precise timing. Another returning finisher is Mercy, last seen in Mortal Kombat Trilogy, where the winning player can opt to revive their opponent after the Finish Him/Her prompt, causing the opponent to gain a small amount of life.', 1, 'MK11', 'NetherRealm Studios', '2019-04-23', 59.99),
('Far Cry 6', 'Similar to the previous entries in the series, Far Cry 6 is a first-person shooter game, set in an open world environment navigable on foot or via various land, water, and air vehicles. Players assume the role of a local rebel named Dani Rojas, a former conscript in the military turned into a guerrilla fighter, whose gender they can select at the start of the game. The world is divided into seven main regions with an array of terrain, ranging from urban areas and dense jungles, to mountain ranges and open oceans. Gameplay focuses on armed and close-quarters combat. Players are able to use a wide array of conventional weapons (such as sidearms, assault rifles, submachine guns, shotguns, light-machine guns, sniper rifles and grenade launchers). Firearms can be customized using materials found throughout the world.

In a new addition to the series, the game features several prototypes of special weaponry, called Resolver weapons, each offering a certain perk to the players loadout, for example a silent close-range nailgun or a sling-shot projectile weapon which fires CDs. Another new addition is the Supremo backpacks, allowing augmentation of the playstyle by assigning more perks to the players loadout, such as firing homing missiles or seeing enemies through solid objects. Unlike the previous titles in the series, players are able to holster weapons; as a result, enemy NPCs will not attack the player on sight, unless within restricted areas.', 1, 'far-cry-6', 'Ubisoft', '2021-10-07', 59.99),
('Death Stranding', 'Death Stranding is an action game set in an open world, and includes asynchronous online functions. Kojima refers to Death Stranding as the first strand game, an original genre characterized by the games incorporation of social elements. Kojima compared this genre to how his earlier game Metal Gear—now considered a stealth game—was called an action game during its release because the stealth genre had not been established.

The player controls Sam Bridges, a porter for a company known as BRIDGES. The player is tasked with delivering supply cargo to various isolated cities known as KNOTs, as well as isolated researchers and survivalists, while also connecting them to a communications system known as the Chiral Network. The player is evaluated by the company and recipients based on their performance (including via likes similar to social networks), including whether the cargo was delivered, and if it is intact, among other factors. These merits are, in turn, used to level up the players statistics, such as stability and weight capacity, and increase their standing with individual locations and characters (which can improve rewards). How cargo is packed by the player, and the overall weight being carried, affect Sams ability to navigate through the environments.', 2, 'death-stranding', 'Kojima Productions', '2019-11-08', 59.99),
('Forza Horizon 5', 'Forza Horizon 5 is a racing video game set in an open-world environment based on a fictional representation of Mexico. The game has the largest map in the entire Forza Horizon series, being 50% larger than its predecessor, Forza Horizon 4, while also having the highest point in the Horizon series. The map was described by creative director Mike Brown as one of the most diverse Forza Horizon maps the team has built. The map contains an active caldera volcano, jungles and beaches, ancient Mayan temples, and towns and cities such as Guanajuato. Players can explore the open world freely, though they can also compete in multiplayer races and complete the campaign mode. Both the cars featured in the game and the player character can be extensively customized. Players are able to create custom liveries and tunes for cars, and perform engine swaps, drivetrain swaps, or install body kits on certain vehicles. The game is the first in the franchise to support ray tracing on cars (although this is only available in Forzavista). The game introduces a new weather system (local weather) in which players can visit one side of the map and can visibly see a storm. Because Mexico is such a vast nation with such a wide range of elevations, multiple climates would appear in the game at around the same time. The four seasons still exist but would affect the eleven unique biomes around the map. For example, in the dry season, dust storms will appear, while tropical storms occur throughout the fall storm season. Another detail is in the jungle, in which the environment would now react to the weather; an example of this is leaves flying everywhere.', 5, 'forza-horizon-5', 'Playground Games', '2021-11-09', 59.99),
('Red Dead Redemption 2', 'Red Dead Redemption 2 is a Western-themed action-adventure game. Played from a first- or third-person perspective, the game is set in an open-world environment featuring a fictionalized version of the United States in 1899. It features single-player and online multiplayer components, the latter released under Red Dead Online. For most of the game, the player controls outlaw Arthur Morgan, a member of the Van der Linde gang, as he completes missions—linear scenarios with set objectives—to progress the story; from the epilogue, the player controls Red Dead Redemption protagonist John Marston. Outside of missions, they can freely roam the interactive world. They may engage in combat with enemies using melee attacks, firearms, bow and arrow, throwables, or dynamite, and can dual wield weapons. The player can swim as Arthur but not as John.', 2, 'red-dead-redemption', 'Rockstar Games', '2018-10-26', 59.99),
('Elden Ring', 'Elden Ring is an action role-playing game set in third-person perspective. It includes elements that are similar to those in other FromSoftware-developed games, such as the Dark Souls series, Bloodborne, and Sekiro: Shadows Die Twice. The game is set in an open world; players can freely explore the Lands Between and its six main areas, which include Limgrave—an area of grassy plains and ancient ruins—and Caelid, a wasteland that is home to undead monsters. The open world is explored using the characters mount Torrent as the main mode of transportation, though players may use fast travel outside combat. Throughout the game, players encounter non-player characters (NPCs) and enemies, including demigods who rule each main area and serve as the games main bosses. Aside from the main areas, Elden Ring has hidden dungeons, catacombs, tunnels, and caves where players can fight bosses and gather helpful items.', 3, 'elden-ring', 'FromSoftware', '2022-02-25', 59.99),
('God of War: Ragnarok', 'God of War Ragnarök is a third-person action-adventure game. It features an over-the-shoulder player-controlled camera, and the game is presented with no camera cuts or loading screens. The gameplay is similar to the previous installment, God of War (2018), including being single-player-only. Throughout the game, players battle Norse mythological foes, with more enemy types than in the prior entry, including newer enemies, such as einherjar, wyverns, stalkers (centaur-like creatures with antlers), phantoms, human raiders, and nøkkens, among many others. The developers also added more mini-bosses to give the game more variety.

The player primarily controls the character Kratos in combo-based combat and puzzle game elements. Kratoss main weapons are a magical battle axe called the Leviathan Axe, and his signature double-chained blades, the Blades of Chaos. He also dons his original Guardian Shield, and utilizes hand-to-hand combat. The Leviathan Axe is infused with ice elemental magic. It can be thrown at enemies and magically summoned back to his hand, similar to Thors hammer Mjölnir. The weapon can be thrown at environmental objects to trigger a damaging explosion, and freeze objects and some enemies in place for puzzle-solving until resummoned. The Blades of Chaos, infused with fire elemental magic, are a pair of blades attached to chains that can be swung around in various maneuvers. A new mechanic for Ragnarök is that the blades can be used like a grappling hook to traverse over chasms, and pick up objects to hurl at enemies. Kratos also obtains a new weapon called the Draupnir Spear, a close- and long-range attack spear that is infused with wind elemental magic and can make copies of itself; Kratos can throw multiple spears at an enemy then have them all explode at once. The spear is also used to traverse or unblock certain pathways. Each weapon has standard light and heavy attacks. They can be upgraded with runes to allow for magical runic attacks, with slots for a light and heavy magical attack, providing a variety of play style options. Additionally, a Weapon Signature Move ability was added, which unleashes a powerful magical attack for the equipped weapon. Another added mechanic is that if on a higher ledge, the player can leap down to perform a powerful weapon attack on enemies below.', 2, 'god-of-war-ragnarok', 'Santa Monica Studio', '2022-11-09', 69.99),
('Horizon Forbidden West', 'Horizon Forbidden West is an action role-playing video game played from a third-person perspective, set in a world populated by dangerous, animalistic machines. The player controls Aloy, a hunter who ventures into an uncharted frontier known as the Forbidden West, a post-apocalyptic version of the Western United States, to investigate a mysterious plague. Aloys primary weapons of choice are bows and arrows. Other weapons in the game include a blastsling, which allows Aloy to slingshot bombs towards enemies, and a Shredder Gauntlet, which launches serrated discs useful for tearing armor and components. She can also lay down traps and tripwires, as well as use the ropecaster to tether enemies to the ground, immobilizing them. Certain weapons in the game have different ammo types, allowing the player to inflict elemental damage on enemies. For instance, acid ammo may melt an opponents armor, while shock ammo can stun enemies. Elemental damage can also be chained. For instance, purgewater arrows may result in a drenched status for a machine, making them more vulnerable to shock arrows and stopping them from unleashing elemental attacks of their own. The elemental status of a machine will gradually accumulate, and the machine will be significantly affected or damaged by that elemental status for a brief period of time once a meter is completely filled. The player can use Aloys Focus to tag an enemy and scan them to identify their weaknesses. Aloy may also detach parts of the machines through her attacks, crippling a large amount of their health, removing their attack capabilities, and occasionally being able to use their own detached weapons against them.', 2, 'horizon-forbidden-west', 'Guerrilla Games', '2022-02-18', 69.99),
('Final Fantasy VII Remake', 'Exploration and battle mechanics both take place in real-time, like Final Fantasy XV. The game features an altered Active Time Battle (ATB) system from the original, which gradually fills up slowly, or can fill faster with attacks. Once it is filled, the player can halt the action and use special abilities such as magic, items, and special moves. The player can assign these special abilities to shortcut buttons, allowing them to play in real-time without pausing. Each special ability uses up a segment of the ATB bar. The player can switch between party members at any time during battle. Each party member has their own individual skills, such as Clouds close-quarters melee attacks and Barrets long-range distance attacks. Players are able to use magic and summons of large creatures, and a Limit Break gauge allows characters to perform more powerful attacks once charged. While the game has more real-time elements, strategic elements still remain, such as selecting weapons and magic for each character to wield', 3, 'final-fantasy-vii', 'Square Enix', '2020-04-10', 59.99),
('Ghost of Tsushima', 'In 1274, a Mongol fleet led by Khotun Khan invades the Japanese island of Tsushima. Local samurai Lord Jin Sakai and his uncle Lord Shimura lead the island samurai in an attempt to repel the invaders. However, the battle ends in disaster, with the samurai killed, Shimura captured, and Jin severely wounded and left for dead. He is found and revived by Yuna, a thief, who informs him that the island has fallen to the invaders. Jin storms Khotun stronghold at Castle Kaneda in an attempt to rescue Shimura but is defeated by Khotun and thrown off the castle bridge.

Realizing he cannot defeat the Mongols alone or with traditional samurai tactics, Jin recruits allies and learns guerrilla warfare. He recruits Yuna, her blacksmith brother Taka, sake merchant Kenji, archer Sadanobu Ishikawa, samurai Masako Adachi, and his mercenary friend Ryuzo along with Ryuzo Straw Hat rōnin. As Jin disrupts Mongol activities and liberates villages, the islanders begin to refer to him as "The Ghost," a samurai spirit that has risen against the Mongols. Taka crafts a grappling hook for Jin to scale Castle Kaneda walls, and Jin attacks the site with his allies. Destitute and starving from harsh wartime conditions, Ryuzo and the Straw Hats betray Jin to collect the bounty issued to him by Khotun. Jin fends them off, frees Shimura, and retakes Castle Kaneda. Despite their victory, Khotun has already left to conquer Castle Shimura with Ryuzo.

To retake Castle Shimura, Jin recruits Norio, Norios warrior monks, and the Yarikawa Clan. He also recruits local pirate Goro on Shimuras behalf to carry a petition for reinforcements and a request to be adopted as his heir to the Shogun. With a new army being assembled, Jin recovers his familys ancestral armor from caretaker Yuriko, who teaches him how to create poison. Under orders from Shimura, Jin and Taka try to infiltrate a fortress where Ryuzo is located but are ambushed and captured by Khotun. When Jin refuses to submit to his rule, Khotun demands Taka kill him in exchange for his freedom. Taka instead attempts to attack Khotun, but he avoids and decapitates him. Jin then escapes with Yuna help. The Shogun reinforcements arrive, and Shimura leads the assembled army in an assault on Castle Shimura, driving the Mongols into the inner keep. As the Mongols retreat, they detonate explosives on the bridge leading to the inner courtyard, inflicting massive casualties on the advancing samurai.', 2, 'ghost-of-tsushima', 'Sucker Punch Productions', '2020-07-17', 59.99),
('Returnal', 'Disobeying orders, ASTRA Corporation pilot and explorer Selene Vassos attempts to land on the off-limits planet of Atropos to investigate what she dubs the "White Shadow" signal, which somehow seems familiar to her. Upon arrival, Selene ship, Helios, suffers heavy damage and crash lands. Unable to contact ASTRA, Selene explores the planet and is shocked when she comes across corpses of herself. She learns that every time she dies, time loops back to the moment she crashed, sending her back to her starting point. The planet seems to change with every loop, and Selene begins experiencing vivid visions.

Resolving to find the source of the White Shadow, Selene presses on, fighting hostile alien lifeforms and scavenging alien technology left over from the advanced, extinct alien civilization that used to reside on Atropos. As she tracks the White Shadow, Selene comes across what appears to be a replica of her childhood home. Every time she enters it, she recalls old memories and repeatedly encounters an astronaut wearing an antique space suit. Selene eventually learns that she apparently used an alien weapon to paradoxically shoot down her own ship, thus making herself responsible for her being marooned on Atropos.

Eventually, Selene tracks down the source of the White Shadow. Afterwards, ASTRA is able to receive her distress call and sends a rescue ship. Selene returns to Earth and eventually dies of old age, only to reawaken back on Atropos, having looped back to the crash. Dismayed that she has failed to escape Atropos, Selene continues to explore the planet. Eventually, her search leads her to an underwater abyss below the planet surface, where she finds a replica of an old car.

She proceeds to the bottom of the abyss where she encounters a massive, octopus-like alien creature. She is then shown a vision of a middle-aged woman, who looks similar to Selene, driving through a forest at night with a young child[b] in the back seat. While passing over a bridge, the woman sees the astronaut standing in the middle of the road and swerves to avoid it, driving the car off the bridge and into the lake below. The woman attempts to reach the now unconscious child but is pulled out of the car by dark cloud-like tentacles. A first-person perspective of the lake surface from below is then shown. The cloud-like tentacles reappear, pulling the viewer away from the surface and deeper into the lake.', 1, 'Returnal', 'Housemarque', '2021-04-30', 69.99),
('Demon''s Souls (Remake)', 'The game features new weapons, armor, rings, and items called Grains which give players a temporary resistance to effects like poison, fire, and bleeding. As with the original, players are limited in how much they can carry before their character becomes encumbered, although some aspects of this encumbrance system have been adjusted. Example: In the original game, all types of moon grass take up 0.1 item burden, in the remake, the item burdens increase upward based on the effectiveness of the grass, from 0.1 per crescent moon grass to 6.0 per dark moon grass. Furthermore, players are given the option to send items to Stockpile Thomas instead of risking items disappearing permanently. One new feature, called Fractured World, is a mirror mode which reverses the layout of environments. The game also includes a photo mode, whereupon using it the game will pause, something not possible in the original. Filters from the photo mode can also be used during gameplay, including a classic mode filter intended to evoke the look of the original PlayStation 3 game. Although the Souls series is notorious for its difficulty, Bluepoint stated that the remake would not introduce different difficulty levels. The character creation feature has also been updated, with more options for customization.', 3, 'DemonSoul', 'Bluepoint Games', '2020-11-12', 69.99),
('Assassin''s Creed Valhalla', 'In 2020, the unexplained strengthening of Earth magnetic field negatively affects the planet. Layla Hassan, Shaun Hastings, and Rebecca Crane receive a signal with coordinates in New England, where they exhume a Viking raider remains. Layla, struggling with the Staff of Hermes Trismegistus influence, enters the Animus to view the raider memories.

In 855 CE in Norway, a young Eivor Varinsdottir witnesses warlord Kjotve the Cruel sacking her hometown and killing her parents before she is rescued by Sigurd, son of King Styrbjorn of the Raven Clan. Seventeen years later, Eivor has been adopted by Styrbjorn, and pursues vengeance against Kjotve. Her latest attempt fails, but she recovers her father axe. Touching it, Eivor experiences a vision of Odin, leading her to consult the local seeress, Valka. Valka induces another vision of Sigurd losing an arm before being consumed by a giant wolf.

Sigurd returns from an expedition with foreigners Basim and Hytham, members of the Hidden Ones, who came to Norway to assassinate Kjotve, a member of the opposing Order of the Ancients. Defying Styrbjorn orders, Eivor and Sigurd enlist King Harald help to eliminate Kjotve. Following their victory, Harald declares his intention to unite Norway under his rule. Styrbjorn pledges fealty to Harald, angering Sigurd, who expected to inherit the crown. He and Eivor take loyalists in the clan on an exodus to England, establishing the settlement of Ravensthorpe. Eivor then secures alliances with neighboring Saxon kingdoms and Viking clans led by Ivar, Halfdan, Ubba Ragnarsson, Guthrum, and Ceolwulf of Mercia, and helps Hytham assassinate local Order members, following tip-offs from a "Poor Fellow-Soldier of Christ."

Eivor visions continue. Valka gives her an elixir that makes her dream of Asgard from Odin perspective. Hoping to avert his own fated death during Ragnarök, Odin imprisons Loki son Fenrir, who is foretold to kill him, and retrieves a magical mead from Jotunheim that will allow him and the other Aesir to be reincarnated. Layla realizes these are actually visions of the Isu shortly before the Great Catastrophe, and that Loki, who was forbidden to reincarnate himself after betraying Odin, found another way to ensure his survival.', 2, 'assassins-creed-valhalla', 'Ubisoft', '2020-11-10', 59.99),
('Halo Infinite', 'In December 2559, the UNSC ship Infinity arrives at Halo Installation 07, only to be ambushed by several dreadnoughts operated by the Banished. The Master Chief defends the ship hangar bay from raiding parties but is caught off-guard by Atriox, the Banished leader, and is defeated in a one-on-one duel. Atriox throws the Chief from the edge of the hangar bay, leaving him stranded in space.

Six months later, a UNSC pilot finds the Chief adrift in space. While the Pilot wants to flee, the Chief insists on continuing the fight against the Banished. They travel to Zeta Halo, heavily damaged by an unknown calamity. On the ring, Master Chief locates the Weapon, an AI designed to imitate Cortana for deletion. The Weapon reveals she failed to self-delete and holds Cortana residual data.

Zeta Halo is controlled by the Banished, now led by Escharum after Atriox apparent death. Escharum, dying, sees the Chief as his final opponent. With the Weapon and a reluctant Pilot, the Chief rallies scattered UNSC forces while searching for surviving Spartans. In the Conservatory, the AI Despondent Pyre warns of a threat but is destroyed by the Harbinger, an alien allied with the Banished. The Harbinger aims to rebuild the Silent Auditorium to free her people, the Endless, imprisoned by the Forerunners on Zeta Halo. The Banished plan to use the Halo as a weapon against humanity.', 4, 'halo-infinite', '343 Industries', '2021-12-08', 59.99),
('Ratchet & Clank: Rift Apart', 'Some time after the events of Into the Nexus, Ratchet and Clank are hailed as heroes during a parade on Corson V, where Clank reveals he has fixed the Dimensionator to aid Ratchet search for the Lombaxes and his family. However, Doctor Nefarious interrupts the festivities, attempting to steal the Dimensionator. In the ensuing chaos, Ratchet accidentally triggers the device, causing dimensional rifts to open and transporting them to an alternate universe.

Separated from each other, Clank finds himself missing an arm and encounters Rivet, a female Lombax. Meanwhile, Nefarious assumes the identity of Emperor Nefarious in this alternate reality. Ratchet, on his own, witnesses Rivet and Clank escape and is aided by Phantom and Glitch in his pursuit. Rivet, initially distrustful of Clank, eventually learns the truth about the dimensional rifts and joins forces with Ratchet and Clank to repair the Dimensionator and prevent further chaos. They collaborate with a prophet named Gary to fix dimensional anomalies and stop the impending Dimensional Cataclysm.', 1, 'ratchet-clank-rift', 'Insomniac Games', '2021-06-11', 69.99),
('The Legend of Zelda: Breath of the Wild', 'In Breath of the Wild, the kingdom of Hyrule is depicted at the end of the Zelda timeline. In ancient times, the Sheikah race had developed an advanced civilization, protected by Divine Beasts and Guardians. When the evil Calamity Ganon threatened Hyrule, four Champions piloted the Divine Beasts while the princess, Zelda, and her appointed knight, Link, fought and sealed Ganon away.

Thousands of years later, Hyrule regressed to a medieval state, and signs of Ganon return prompted the excavation of the Divine Beasts and Guardians. Princess Zelda trained to awaken her sealing magic, and Link, chosen for his ability to wield the Master Sword, was appointed as her protector. The Champions assembled to pilot the Divine Beasts, but Ganon possessed them, leading to devastation across Hyrule.

Ganon appearance on Zelda seventeenth birthday resulted in the death of King Rhoam and the Champions, widespread destruction, and Link being gravely wounded. Zelda unlocked her sealing powers to save Link, hid the Master Sword, and sealed herself and Ganon in Hyrule Castle, an event known as the Great Calamity.', 2, 'botw', 'Nintendo', '2023-12-31', 69.99),
('The Legend of Zelda: Tear of Kingdom', 'In "Tears of the Kingdom," set years after Breath of the Wild, Link and Zelda explore a cavern beneath Hyrule Castle, where they encounter a mural depicting Hyrule founding and the Imprisoning War against the "Demon King." Venturing deeper triggers the awakening of a mummy, resulting in Link right arm being wounded, the Master Sword shattering, and Hyrule Castle being raised into the sky. Zelda falls below, vanishing with a mysterious artifact, while Link is rescued by a disembodied arm, which becomes his new limb. Guided by the spirit of Rauru, a Zonai, Link traverses the Great Sky Island and eventually dives to the surface below.

In the wake of the Upheaval, chaos ensues in Hyrule, prompting Link to investigate strange phenomena alongside allies like Sidon, Tulin, Yunobo, and Riju. They explore ancient Zonai temples, defeat monsters, and encounter artifacts containing the spirits of ancient sages, who appoint Link allies as their successors. After encountering an impostor Zelda serving Ganondorf, Link defeats her with the help of his allies. He then sets out to find the last ancient sage, Mineru, and assists in creating a mechanical body for her spirit.', 2, 'tokd', 'Nintendo', '2023-05-12', 69.99),
('Gran Turismo 7', 'Gran Turismo 7 brings back the GT Simulation Mode, offering players a single-player campaign experience reminiscent of previous titles in the series. Alongside this, traditional racing tracks, vehicles, Special Events, Championships, Driving School, Tuning Parts Shop, Used Cars dealership, GT Auto, GT Sport Mode, Brand Central, and Discover (now labelled Showcase) from Gran Turismo Sport also make a return.

Players progress through tasks in the GT Café, known as "Menu Books," to unlock various features, including multiplayer, tracks, and cars. The game reintroduces dynamic time and weather effects, enhancing the racing experience. However, similar to Gran Turismo Sport, a constant internet connection is required to save progress, aimed at preventing hacking and cheating. Arcade mode remains fully playable offline, offering a convenient option for those without internet access.', 5, 'gran-turismo-7', 'Polyphony Digital', '2022-03-04', 69.99),
('Call of Duty: Modern Warfare II', 'In July 2022, Task Force 141, commanded by General Herschel Shepherd, carries out a precise missile strike targeting Russian-supported Iranian forces. This operation results in the assassination of Iranian General Ghorbrani during an arms deal in Al Mazrah. Later, in October, Ghorbrani lieutenant, Quds Force Major Hassan Zyani, becomes involved in financing terrorist activities and seeks retaliation against the United States.

CIA Station Chief Kate Laswell and General Shepherd assign Marine Raiders, led by Task Force 141 members Lieutenant Simon "Ghost" Riley and Sergeant John "Soap" MacTavish, to apprehend Hassan in Al Mazrah. Despite their efforts, Ghost and Soap fail to capture Hassan but discover that he possesses an American ballistic missile.

Laswell, along with Task Force 141 operatives Captain John Price and Sergeant Kyle "Gaz" Garrick, pursue one of Hassan couriers in Amsterdam. They learn that Hassan has formed an alliance with the Las Almas Cartel and is currently in Mexico. Despite a failed attempt to apprehend Hassan at the Mexico–US border, a joint operation with Mexican Special Forces Colonel Alejandro Vargas and his unit Los Vaqueros, along with Ghost, Soap, and Shadow Company, is launched to capture Hassan successfully.

However, due to political considerations with Iran, Hassan is released since conclusive evidence to arrest him is lacking. Subsequent data retrieved from Hassan phone leads Price, Laswell, and Gaz to Cape Vilan, where they discover that Las Almas has Russian-made GPS devices for missiles. Laswell is then captured by the Urzik terrorist group Al-Qatala, prompting Price and Gaz to rescue her with the assistance of their allies Nikolai and Farah Karim.

Meanwhile, Alejandro and Soap capture Las Almas leader "El Sin Nombre," later revealed to be Alejandro former special forces comrade Valeria Garza. Valeria discloses that one of the missiles is located on an oil rig in the Gulf of Mexico, triggering a raid by Task Force 141, Shadow Company, and Alejandro to prevent its launch. Despite the success of the mission, Shepherd and Shadow Company betray Task Force 141 under Shepherd orders. Graves captures Alejandro and seizes Los Vaqueros’ base, while Ghost and Soap, with assistance from Rodolfo, Laswell, Price, and Gaz, rescue Alejandro and Los Vaqueros from Shadow Company onslaught.', 4, 'call-of-duty-modern-warfare', 'Infinity Ward', '2022-10-28', 69.99),
('FIFA 23', 'In FIFA 23, players enjoy the culmination of a long-standing partnership between EA Sports and FIFA, marking the 30th installment in the celebrated series. Released globally on September 30, 2022, across various platforms including Nintendo Switch, PlayStation 4, PlayStation 5, Windows, Xbox One, and Xbox Series X/S, the game features Kylian Mbappé and Sam Kerr as the cover athletes for the standard and legacy editions.

Regarded as the best-selling sports video game franchise worldwide, FIFA holds a prominent place in gaming history. However, the release of FIFA 23 also marks the end of an era, as it concludes the 29-year partnership between EA and FIFA. Following the loss of licensing from FIFA in late 2023, future football games by EA will adopt a new moniker under the banner of EA Sports FC (EAFC, EASFC, or FC24), signifying a fresh chapter in the evolution of football gaming.', 6, 'fifa-23', 'EA Sports', '2022-09-30', 59.99),
('NBA 2K23', 'NBA 2K23 introduces the highly anticipated return of the Jordan Challenge, a beloved feature last seen in NBA 2K11. This iconic mode transports players back to the basketball landscape of 1982, where they can immerse themselves in legendary matchups featuring none other than Michael Jordan himself.

Furthermore, MyNBA receives a significant overhaul, providing players with the opportunity to embark on their MyNBA career across various NBA seasons, including 1983–84, 1991–92, 2002–03, or the current 2022–23 season. Notably, the game offers automatic team relocations reminiscent of real-life NBA history, such as the Kansas City Kings moving to Sacramento, the Vancouver Grizzlies relocating to Memphis, and the Seattle SuperSonics making the move to Oklahoma City. However, players retain the ability to veto these relocations if they choose.

The "eras" mode within MyNBA delivers a richly detailed experience, featuring fully rendered arenas, logos, and jerseys from the 1980s, 1990s, and 2000s, complete with historic rosters and draft classes. Additionally, the mode incorporates television filters and broadcast packages that faithfully emulate the broadcasting styles of each respective era, including the NBA on CBS, NBA on NBC, and ESPN broadcasts. These broadcast packages also extend to the Jordan Challenge mode, further enhancing the nostalgic atmosphere.

Moreover, historical rule changes have been implemented, allowing players to modify or introduce new rules that reflect the gameplay nuances of each NBA era. This adds depth and authenticity to the MyNBA experience, empowering players to customize their simulation gameplay during the offseason.

Overall, NBA 2K23 offers a comprehensive and immersive basketball gaming experience, blending nostalgia with modern features to cater to both longtime fans and newcomers alike.', 6, 'NBA_2k23', 'Visual Concepts', '2022-09-09', 59.99),
('Battlefield 2042', 'Battlefield 2042 continues the tradition of being a multiplayer-focused first-person shooter, but with a futuristic twist set in the near future. Players are armed with advanced weapons and gadgets, including deployable turrets and drones, and have access to a variety of vehicles that they can control. One notable addition is the ability for players to request vehicle air-drops to any location, enhancing strategic options on the battlefield.

A significant overhaul to the class system introduces the "Plus" system, allowing players to customize their weapons on the fly. Instead of predefined classes, players assume control of specialists who embody the traditional Battlefield gameplay classes of Assault, Engineer, Medic, and Recon. Each specialist comes with unique skills and gadgets, offering diverse playstyles. For example, Emma "Sundance" Rosier is equipped with a wingsuit, while Maria Falck wields a healing pistol.

Battlefield 2042 brings back Levolution and destructive environments from Battlefield 4, along with extreme weather effects like tornadoes and sandstorms that can dynamically impact gameplay. The game features seven maps at launch, including the expansive Breakaway, which is touted as the largest map in Battlefield history.

The game offers three main gameplay modes: "All-Out Warfare," which includes the staple modes of "Conquest" and "Breakthrough." In Conquest, teams compete to capture control points, while Breakthrough involves one team attacking and the other defending control points. Both modes support matches with up to 128 players on PlayStation 5, Windows, and Xbox Series X/S, and up to 64 players on PlayStation 4 and Xbox One. Cross-platform play is supported between PlayStation 5, Windows, and Xbox Series X/S versions, with limited support for PlayStation 4 and Xbox One players restricted to their respective platforms.', 4, 'battlefield-2042', 'DICE', '2021-11-19', 69.99),
('Forspoken', 'Frey journey begins in a world vastly different from her own, Athia, where she discovers newfound powers awakened by a sentient bangle named Cuff. This world is plagued by the Break, a corruptive force threatening all life except Frey, who seems immune to its effects.

Upon arriving in Athia, Frey finds refuge in the city of Cipol, humanity last bastion against the Break. However, her unusual resistance to the corruptive force raises suspicion among the ruling council, leading to her imprisonment. With the help of a citizen named Auden, Frey manages to escape to the slums, where she begins to navigate the intricacies of this unfamiliar world.

As Frey adapts to her newfound abilities and the challenges of Athia, she encounters various obstacles and allies on her journey. With Cuff by her side and her determination to unravel the mysteries of Athia, Frey sets out to confront the looming threat of the Break and uncover her role in this enigmatic realm.', 3, 'forspoken', 'Luminous Productions', '2023-01-24', 69.99),
('The Witcher 3: Wild Hunt', 'Geralt journey to find Ciri takes him to various regions, each fraught with its own challenges and dangers. In White Orchard, he confronts a griffin and assists the Nilfgaardian garrison before meeting with Yennefer, who reveals Emperor Emhyr request to find their adopted daughter, Ciri. Ciri, a Child of the Elder Blood with the power to manipulate time and space, is pursued by the Wild Hunt, a mysterious and malevolent force.

In Velen, Geralt seeks information about Ciri from the Bloody Baron, who demands help finding his missing family in exchange. Geralt discovers that Ciri was briefly held captive by the Crones, three sinister witches ruling over the region, before escaping to Novigrad. In Novigrad, Geralt reunites with Triss Merigold, who aids him in rescuing their mutual friend Dandelion. Dandelion reveals that Ciri escaped to avoid capture by the city authorities.

Throughout his journey, Geralt encounters familiar faces and uncovers clues about Ciri whereabouts while navigating political intrigue, supernatural threats, and personal relationships. As he delves deeper into the mystery surrounding Ciri and the Wild Hunt, Geralt path becomes increasingly perilous, leading him to confront powerful adversaries and make difficult choices that will shape the fate of the world.', 3, 'the-witcher-3', 'CD Projekt Red', '2015-05-19', 39.99),
('Mass Effect Legendary Edition', 'Mass Effect Legendary Edition is a comprehensive collection that encompasses the single-player base content from all three games in the Mass Effect trilogy: Mass Effect, Mass Effect 2, and Mass Effect 3. In addition to the main campaigns, it includes nearly all single-player downloadable content (DLC) originally released for each game, comprising promotional weapons, armors, and packs.

At its core, the trilogy offers action role-playing experiences where players embody the role of Commander Shepard, an elite human soldier entrusted with the monumental task of uniting the diverse galactic community against the existential threat posed by the Reapers. These Reapers are an advanced race of synthetic-organic starships bent on harvesting all organic life in the galaxy.

Commander Shepard is a customizable protagonist, allowing players to define their gender, appearance, military background, combat training, and even their first name. Throughout the trilogy, players navigate a complex narrative, making choices that significantly impact the storyline and shape the relationships between characters. These decisions carry consequences that reverberate throughout the trilogy, providing a deeply immersive and personalized gameplay experience.', 3, 'mass-effect-dark', 'BioWare', '2021-05-14', 59.99),
('Diablo IV', 'In Diablo IV, set in the dark and foreboding world of Sanctuary, the storyline unfolds 50 years following the tumultuous events depicted in Diablo III: Reaper of Souls. At the heart of the narrative lies the sinister presence of Lilith, daughter of the malevolent demon Mephisto, who has been summoned by a group of cultists.

With the balance of power shifted in the aftermath of previous conflicts, both the forces of demons and angels have weakened, creating an opportune moment for Lilith to assert her dominance over Sanctuary, the world where the game is set.

The origins of Sanctuary trace back thousands of years, when Lilith and the angel Inarius collaborated to create a refuge from the unending strife between the High Heavens and the Burning Hells. This union gave birth to the Nephalem, a unique race embodying characteristics of both angels and demons. As Sanctuary flourished, fears arose among its inhabitants that the Nephalem extraordinary powers would draw unwanted attention and provoke their destruction. In a bid to protect her children, Lilith resorted to drastic measures, eliminating any who opposed her rule. This action ultimately led to her banishment by Inarius to the void, setting the stage for the events that unfold in Diablo IV.', 3, 'diablo-iv', 'Blizzard Entertainment', '2023-06-06', 69.99),
('Star Wars Jedi: Survivor', 'Five years have passed since Jedi Knight Cal Kestis destroyed the Jedi Holocron. In that time, he has chosen to continue his fight against the oppressive Empire, working alongside Saw Gerrera as a resistance fighter. Together with his former allies Cere Junda, Greez Dritus, and Merrin, Cal embarks on a daring mission to the heart of the Imperial capital world, Coruscant. Their objective: to steal vital military data from Senator Daho Sejan.

However, their operation takes a devastating turn when the Ninth Sister, a formidable Inquisitor thought defeated, reemerges to exact vengeance on Cal. In the ensuing confrontation, Sejan and most of Cal team are slain, leaving him to face the Ninth Sister alone. Despite emerging victorious, Cal is left disheartened upon discovering from the stolen data that the Empire has only grown more powerful, extending its grip across the galaxy.

With the Stinger Mantis, their ship, severely damaged during the escape from Coruscant, Cal seeks out Greez on the remote planet of Koboh for repairs. However, their arrival coincides with the planet residents facing threats from the Bedlam Raiders, a criminal syndicate led by the formidable Rayvis. As Cal sets out to repair the Mantis, he finds himself drawn into a new conflict, determined to aid the locals against the tyranny of the Bedlam Raiders.', 2, 'star-wars-jedi', 'Respawn Entertainment', '2023-04-28', 69.99),
('Evil West', 'Jesse Rentier, an agent of the Rentier Institute, finds himself embroiled in a dangerous mission to combat supernatural creatures known as Sanguisuge, or "Ticks." Alongside retired agent Edgar Gravenor, they intercept a vampire informant named Chester Morgan, gathering crucial information about the smuggling operations of blood and lower Sanguisuge beasts. Their investigation leads them to Peter D.Abano, a Highborn vampire advocating for evolving the Sanguisuge through controlling the "Change" found in blood, and declaring war on humanity.

Despite opposition from the Sanguisuge leadership, who reject D.Abano radical plan, Jesse and Edgar successfully capture D.Abano head, intending to add it to the Institute Archives of slain Sanguisuge. However, upon returning to the Institute headquarters, Jesse confronts his father, William, about his future within the organization.

Their plans are disrupted when D.Abano daughter, Felicity, launches a deadly assault on the Manor, killing many and retrieving her father head. With William gravely injured, Jesse, Edgar, and Assistant Secretary of War James Harrow flee to Calico, seeking aid from the local Rentier Institute cell led by Dr. Emilia Blackwell.

As Edgar seeks a possible cure for William condition, Jesse collaborates with engineer Vergil Olney to repair a critical piece of equipment, the Gauntlet, essential for combating the Sanguisuge threat. With tensions rising and danger looming, Jesse must navigate treacherous waters to protect humanity from the encroaching darkness of the Sanguisuge.', 1, 'evil-west', 'Flying Wild Hog', '2022-11-22', 49.99),
('Bayonetta 3', 'In an alternate universe, Bayonetta battles against Singularity but is ultimately defeated, leaving Viola to witness her demise and inherit the last remnants of her power. Commanded by her officer Sigurd, Viola utilizes a world bridge to escape to another universe, seeking aid in the fight against Singularity. As Viola flees, Sigurd falls in battle, and she arrives in a universe where Bayonetta and Jeanne witness the onslaught of the Homunculi upon New York City.

Finding refuge in Rodin bar, the Gates of Hell, Viola explains the dire situation to Bayonetta and seeks her help in confronting Singularity. Together, they learn from Rodin that Singularity ultimate goal is to gain control over all realities by causing their collapse. To prevent this, they must collect the Chaos Gears, which can lead them to the "Alphaverse" where Singularity resides. Meanwhile, Jeanne is tasked with locating their universe version of Sigurd, a scientist with crucial knowledge about the multiverse.

Their journey takes them to the island of Thule, a gateway between universes, where they battle across various alternate realities. Along the way, Bayonetta confronts alternate versions of herself, each protecting their own world, and absorbs their power after defeating them. Viola, on the other hand, pursues Luka, who has been following them throughout the multiverse. She discovers that the loss of his alternate counterparts has transformed Luka into a ferocious beast named Strider, driven by the rage of the Alphaverse Dark Adam.

As their quest unfolds, Viola reveals her surprising lineage as the daughter of her universe Bayonetta and Luka. They encounter an alternate version of Luka known as "Lukaon," the king of the faeries, who possesses vital knowledge of the multiverse. Eventually, Jeanne successfully retrieves their universe Sigurd, and they use the Chaos Gears to open a portal into the Alphaverse.

Upon entering the Alphaverse, they confront Singularity, whose true identity is revealed to be their universe Sigurd—an artificial human consumed by a desire for ultimate power over the multiverse. Together, Bayonetta and Viola must confront this formidable foe to prevent the collapse of all realities and safeguard the future of existence.', 1, 'bayonetta-3', 'PlatinumGames', '2022-10-28', 59.99),
('Sonic Frontiers', 'Doctor Eggman ventures to the desolate Starfall Islands with the intention of plundering the technological secrets left behind by the Ancients, beings associated with Chaos. However, his plans go awry when his artificial intelligence unit, Sage, inadvertently triggers a defense mechanism, transporting Eggman into a digital realm known as Cyber Space.

Meanwhile, Sonic, Tails, and Amy investigate the islands due to unusual activity involving the Chaos Emeralds. Their aircraft is pulled into a wormhole, leading them into Cyber Space. Sonic manages to escape back to the real world, where he encounters a mysterious voice instructing him to retrieve the emeralds and dismantle the island robotic Titans to bridge the gap between reality and the digital realm. Sonic believes that by doing so, he can rescue his friends, including Knuckles, who is also trapped in Cyber Space after exploring the ruins above Angel Island.

As Sonic progresses, he discovers that destroying the cages holding his friends digital forms results in his own body becoming increasingly corrupted. Sage, the AI responsible for imprisoning Eggman, initially opposes Sonic efforts but gradually grows to sympathize with him as it observes his interactions with his friends. It even develops a familial bond with Eggman, who is also trapped in Cyber Space.

Through visions provided by the local Koco, Sonic and his friends learn about the history of the Ancients. They discover that the Ancients were an extraterrestrial race whose planet was destroyed by a powerful entity known as The End. Escaping to Earth with the aid of the Chaos Emeralds, the Ancients sought refuge, but The End followed, threatening their new home. To contain The End, the Ancients constructed the Titans and sealed it within Cyber Space. The Koco, holding the essence of the Ancients, guide Sonic and his friends, and they help fulfill the Koco final wishes, allowing their essences to rest peacefully.', 1, 'sonic-frontiers', 'Sega', '2022-11-08', 59.99),
('Alan Wake 2', 'The game begins with a haunting monologue by Alan, showing him with a mysterious glowing hole in his forehead. A naked man emerges from Cauldron Lake, experiencing disturbing visions before being brutally murdered by a group of masked men.

FBI Special Agent Saga Anderson and her partner Alex Casey are sent to Bright Falls to investigate a series of ritualistic murders, including the latest victim, former FBI agent Robert Nightingale. They discover a strange manuscript page that appears to predict future events. As they delve deeper into the investigation, they encounter Sheriff Tim Breaker and waitress Rose Marigold, who seems to recognize Saga despite it being her first visit to the town. Nightingale corpse unexpectedly reanimates and escapes, leading Saga and Casey on a chase to Cauldron Lake.

Casey reveals his prior investigation into a murder cult in New York dedicated to bringing back Alan Wake, the missing author, by reenacting murders from his books. Saga encounters Nightingale, transformed into a "Taken," and is forced to kill him. They find Alan Wake washed up on the lake shore and take him into custody. Alan recounts his escape from the Dark Place, a dream-like dimension.

Trapped in the Dark Place, Alan discovers a lamp that allows him to manipulate his surroundings. He navigates a twisted version of New York, following the trail of his evil doppelganger, Mr. Scratch, who leads a cult dedicated to the written word. Along the way, Alan encounters Breaker, searching for a mysterious figure named Mr. Door. Alan also communicates with Saga, exchanging vital information. After mistakenly believing he killed Tom Zane, another captive of the Dark Place, Alan is confronted by an alternate version of himself, revealing the consequences of his attempts to escape.', 1, 'alan-wake-2', 'Remedy Entertainment', '2023-10-17', 59.99),
('Baldur''s Gate III', 'Baldur Gate 3 unfolds in the vast and fantastical world of the Forgotten Realms, specifically during the year 1492 DR. This setting places it more than 120 years after the events of its predecessor, Baldur Gate II: Shadows of Amn, and follows shortly after the playable Dungeons & Dragons 5e module, Baldur Gate: Descent into Avernus.

The narrative primarily unfolds across the Sword Coast, located in western Faerûn. This region is rich with diverse landscapes and locales, including the Emerald Grove, a sacred druid grove dedicated to the deity Silvanus. However, this natural beauty is contrasted by the Shadow-Cursed Lands, shrouded in an eerie darkness that possesses sentience, and Moonrise Towers, which are enigmatic structures surrounded by mystery.

Central to the story is Baldur Gate itself, a bustling and prosperous city that serves as a hub of activity and intrigue. Surrounding Baldur Gate is the suburban area of Rivington, which also plays a role in the unfolding events.

As the player embarks on their journey, they will traverse not only the familiar landscapes of the Sword Coast but also delve into more mysterious and dangerous realms. These include the treacherous depths of the Underdark, the ethereal realm of the Astral Plane, and even the fiery plains of Avernus, a layer of the Nine Hells.

Through these diverse and immersive environments, players will encounter a wide array of challenges, allies, and adversaries as they unravel the mysteries of Baldur Gate 3.', 3, 'baldurs-gate-3', 'Larian Studios', '2023-08-03', 59.99),
('Bloodborne', 'In "Bloodborne," the player takes on the role of a Hunter who undergoes a mysterious blood transfusion, setting them on a perilous journey through the cursed city of Yharnam. The narrative unfolds with the Hunter awakening in a clinic and encountering various cryptic figures, including Gehrman and the Doll, who guide them in their quest to end the plague of beasts that ravages the city.

As the Hunter explores Yharnam, they encounter formidable foes like Father Gascoigne and Vicar Amelia, and delve into forbidden places such as Byrgenwerth and the Forbidden Woods. Along the way, they uncover dark secrets about the Healing Church connection to the blood ministration and the enigmatic Great Ones, powerful beings worshipped by the scholars of Mensis.

The journey takes the Hunter to the Nightmare realms, where they confront otherworldly entities and face off against Micolash, the deranged head of the School of Mensis. Ultimately, the Hunter encounters Mergo, the source of the Nightmare, and their guardian, in a climactic showdown.

Throughout the game, the Hunter perception is heightened, allowing them to navigate the treacherous landscapes of Yharnam and uncover the truth behind the city descent into madness. With each victory over formidable adversaries and each revelation about the city dark history, the Hunter inches closer to their goal of ending the nightmare plaguing Yharnam and escaping its grasp.', 3, 'bloodborne', 'FromSoftware', '2015-03-24', 59.99),
('Control', 'In "Control," Jesse Faden embarks on a quest to locate her brother, Dylan, who has been abducted. Upon arriving at the Oldest House, the headquarters of the Federal Bureau of Control (FBC), Jesse is thrust into a chaotic situation where the building is under siege by a mysterious force known as the Hiss. She discovers that the previous director, Zachariah Trench, has been killed, and she is chosen by an enigmatic entity called Polaris to become the new director.

Armed with Trench Service Weapon and aided by survivors wearing Hedron Resonance Amplifiers (HRAs), Jesse sets out to reclaim the Oldest House from the Hiss. She communicates with Trench through an Object of Power called the Hotline and learns about the secrets of the Bureau. Along the way, Jesse encounters other members of Trench management team, including Helen Marshall, who helps her understand the nature of Dylan abilities and his connection to the Hiss.

Jesse delves into the depths of the Oldest House, navigating through its labyrinthine corridors and facing off against possessed agents and formidable entities. She learns about the slide projector Object of Power, which serves as a gateway to an alternate dimension known as Slidescape-36, where Trench and Bureau scientist Dr. Casper Darling discovered Polaris.

As Jesse progresses, she confronts Dylan, who has embraced the Hiss. She discovers that Trench was the first to be possessed by the Hiss and inadvertently unleashed it into the Oldest House. With Ahti guidance, Jesse ventures into Slidescape-36 and encounters Polaris, who helps her regain control over her mind and resist the Hiss influence.

In a climactic showdown, Jesse deactivates the slide projector and seemingly cleanses Dylan of the Hiss, preventing the entity from overtaking the Astral Plane. Although the Oldest House remains infested by the Hiss, Jesse accepts her role as director and vows to work with the surviving FBC personnel to find a solution and restore order to the Bureau.', 2, 'control', 'Remedy Entertainment', '2019-08-27', 59.99),
('Destiny 2', 'In "Destiny 2," the narrative unfolds in the aftermath of the devastating attack on the Last City by the Red Legion, a Cabal faction led by Dominus Ghaul. The assault results in the destruction of the Tower, the central hub for Guardians, and the severing of their connection to the Light, the source of their power.

The player Guardian, stripped of their abilities, embarks on a journey to reclaim their lost powers and rally forces to resist the Red Legion tyranny. With the help of Suraya Hawthorne and other survivors, they establish a new base of operations in the European Dead Zone called "the Farm." Guided by a vision, the Guardian discovers a shard of the Traveler hidden within the EDZ, which restores their connection to the Light.

Upon regaining their powers, the Guardian assists the Vanguard in mounting a counter-offensive against the Red Legion. They travel to various locations across the solar system, including Titan, Nessus, and Io, to reunite with key allies like Zavala, Ikora Rey, and Cayde-6. Along the way, they learn about Ghaul plans to harness the Light and ascend as the new ruler of the Cabal Empire.

The Vanguard devises a plan to stop Ghaul by neutralizing the Almighty, the Red Legion superweapon positioned near the Sun. The Guardian infiltrates the Almighty and disables the weapon, prompting a full-scale assault on the Red Legion forces. However, Ghaul, driven by his desire to claim the Light, betrays his mentor, the Consul, and kills the Speaker to seize control of the Traveler power.

As Ghaul prepares to take the Light by force, the Guardian and their allies confront him in a climactic battle to reclaim the Last City and defeat the Red Legion. With the aid of the Traveler and their restored powers, the Guardian emerges victorious, thwarting Ghaul ambitions and restoring hope to humanity.', 4, 'Destiny2', 'Bungie', '2017-09-06', 0.00),
('Final Fantasy XVI', 'Clive journey is fraught with tragedy, betrayal, and a relentless pursuit of justice. As a teenager, he witnesses the death of his father and the awakening of his brother Joshua destructive powers as the Phoenix. Driven by a desire for revenge and justice, Clive finds himself enslaved to the very forces that betrayed his family. However, his loyalty to his brother and his determination to right the wrongs inflicted upon him lead him on a path of redemption and self-discovery.

Throughout his quest, Clive confronts his own inner turmoil, grappling with the knowledge that he is Ifrit, the very Eikon responsible for his brother demise. Yet, with the guidance of companions like Jill and Cid, he learns to accept his dual nature and harnesses the power of other Eikons to combat the forces of oppression and tyranny.

As Clive and his allies embark on a mission to destroy the Mothercrystals, symbols of power and oppression, they face formidable adversaries and heartbreaking losses. Clive transformation into "Cid" symbolizes his evolution from a vengeful youth to a determined leader, carrying on the legacy of his fallen mentor and continuing the fight for justice and freedom.

In the final confrontation with Hugo, Clive confronts his past and embraces his destiny as the bearer of Ifrit. With his newfound control over his powers and unwavering resolve, he vanquishes his foe and destroys the source of oppression, bringing an end to the cycle of suffering and paving the way for a new era of hope and reconciliation.

Clive journey is a testament to the power of resilience, determination, and the enduring bond of family and friendship. Despite the challenges and sacrifices he faces along the way, he emerges as a beacon of hope and a symbol of strength, inspiring others to rise up and fight for a better future.', 3, 'final-fantasy-xvi', 'Square Enix', '2023-06-22', 69.99),
('Gears 5', 'Delta Squad journey is marked by personal and moral dilemmas as they navigate the treacherous landscape of war and betrayal. The revelation of JD past actions during the riot in Settlement 2 shakes the foundation of trust within the team, leading to fractures in their relationships and doubts about their allegiances.

Kait journey of self-discovery takes center stage as she grapples with her identity and connection to the Swarm. Her vivid visions and ancestral ties to Queen Myrrah unveil a complex web of genetic experimentation and manipulation, thrusting her into a position of unexpected leadership and responsibility.

The exploration of New Hope and Mount Kadar reveals the sinister origins of the Locust and the true extent of Niles Samson unethical experiments. Kait confrontation with her past and her lineage as a potential queen of the Swarm underscores the moral complexities of war and the blurred lines between friend and foe.

As the threat of Reyna ascension to the position of Swarm queen looms large, Kait and Del must confront their inner demons and make difficult decisions to protect humanity. Their determination to reactivate the Hammer of Dawn reflects their unwavering commitment to saving their people, even in the face of overwhelming odds and personal sacrifices.

Throughout their journey, Delta Squad grapples with themes of loyalty, redemption, and the consequences of their actions. As they confront their pasts and forge a path forward, they must rely on each other and their shared resolve to confront the looming threat of the Swarm and secure a future for humanity.', 4, 'Gears5', 'The Coalition', '2019-09-10', 59.99),
('Ghostwire: Tokyo', 'As Akito grapples with the shocking revelation of KK fate, he must navigate the treacherous streets of Shibuya alone, facing off against Hannya minions and unraveling the mysteries surrounding the enigmatic antagonist dark plans. With Mari life hanging in the balance and the fate of Shibuya at stake, Akito must muster all his courage and resourcefulness to confront Hannya and thwart his nefarious scheme.

As he delves deeper into the shadowy underworld of spirits and ancient rituals, Akito encounters allies and enemies alike, each with their own agendas and secrets. Along the way, he uncovers the tragic history of Hannya and the events that led to his descent into darkness, shedding light on the motivations driving his relentless pursuit of power.

Armed with newfound knowledge and determination, Akito embarks on a perilous journey to rescue his sister and put an end to Hannya reign of terror. But as he faces increasingly formidable challenges and confronts the true extent of Hannya power, Akito must confront his own inner demons and make difficult choices that will shape the fate of Shibuya and its inhabitants.

With the help of unlikely allies and the strength of his own spirit, Akito ventures into the heart of darkness to confront Hannya and bring an end to the nightmare that has engulfed his city. In a final showdown against his formidable foe, Akito must tap into the full extent of his powers and courage to emerge victorious and restore peace to Shibuya once and for all.', 2, 'ghostwire-tokyo', 'Tango Gameworks', '2022-03-25', 59.99),
('Hades', 'Zagreus journey in "Hades" is a compelling exploration of family, identity, and the pursuit of freedom in the face of seemingly insurmountable obstacles. His quest to escape the Underworld is not just about physical liberation but also about discovering the truth of his origins and reconnecting with his mother, Persephone.

Throughout the game, Zagreus is confronted with challenges and adversaries, both within the Underworld and among the gods of Olympus. His determination to defy his father, Hades, and seek out Persephone is fueled by a deep longing for connection and understanding. Despite the risks and hardships he faces, Zagreus persists, aided by allies like Nyx and the Olympian gods who offer their support and guidance.

The revelation of Zagreus true parentage adds layers of complexity to his journey, as he grapples with the implications of his divine lineage and the circumstances surrounding his birth. His reunion with Persephone is a poignant moment of reconciliation and acceptance, as mother and son come to terms with their shared past and the sacrifices they have made.

The game narrative also delves into the dynamics of power and responsibility within the divine realm, highlighting the tensions between Hades and the other Olympian gods. Persephone return to the Underworld signals a shift in the balance of power and sets the stage for future developments as Zagreus continues his quest for freedom.

Ultimately, "Hades" is not just a tale of escape but a story of self-discovery and redemption, as Zagreus forges his own path and redefines his relationships with both his family and his destiny. It a journey filled with heart, humor, and epic battles, inviting players to delve into a richly imagined world steeped in myth and legend.', 1, 'hades', 'Supergiant Games', '2020-09-17', 24.99),
('Marvel''s Spider-Man 2', 'Peter life takes a tumultuous turn as he juggles his responsibilities as a physics teacher at Brooklyn Visions Academy with his duties as Spider-Man. The unexpected appearance of Sandman disrupts his first day of teaching, leading to a confrontation that ultimately costs him his job. Returning to Aunt May home in Queens, Peter finds himself at a crossroads, grappling with his new circumstances and the loss of his beloved aunt.

However, Peter world is further complicated by the miraculous recovery of his friend Harry, who offers him a job at the Emily-May Foundation, a startup dedicated to environmental technology. As Peter navigates his budding career alongside his personal life, he finds himself drawn into a dangerous game orchestrated by Kraven and his Hunters, who are targeting super-powered individuals.

The revelation of Harry own super-powered abilities, courtesy of a transformative exosuit developed by Curt Connors, adds another layer of complexity to Peter challenges. As Harry powers grow, so too does the threat posed by Kraven, whose obsession with hunting powerful beings puts Peter and his loved ones in jeopardy.

With the stakes higher than ever, Peter must confront his own limitations and fears as he battles Kraven and his Hunters to protect his city and those he holds dear. As the conflict escalates, Peter resolve is tested, leading to a dramatic showdown that will determine the fate of New York and the lives of its inhabitants.

Through it all, Peter must navigate the complexities of friendship, loyalty, and duty, as he strives to uphold the legacy of his beloved Aunt May and honor the memory of those who have come before him.', 2, 'marvelspiderman2', 'Insomniac Games', '2023-10-20', 69.99),
('No Man''s Sky', 'The Traveller journey in "No Man Sky" is a profound exploration of identity, purpose, and the mysteries of the universe. Awakening on a remote planet with no memory, the Traveller embarks on a quest to uncover the truth about their existence and the enigmatic forces guiding them towards the centre of the galaxy.

As they traverse the cosmos, the Traveller encounters diverse alien species, each with their own culture, knowledge, and wisdom. Along the way, they form alliances, seek guidance from mysterious entities like Nada and Polo, and communicate with fellow Travellers such as Artemis and Apollo, each adding layers to the unfolding narrative.

The discovery of Artemis, a fellow Traveller trapped in a sunless world, serves as a catalyst for the Traveller quest, prompting them to unravel the secrets of ancient portals and the Sentinels guarding the galaxy. Through encounters with cosmic entities like the Atlas and -null-, the Traveller is confronted with existential dilemmas and moral choices, grappling with the implications of their actions on the fate of others.

The revelation of Artemis fate and the discovery of the dying Atlas underscore the transient nature of life and the vastness of the universe. The Traveller encounters with death, loss, and sacrifice resonate deeply as they navigate the complexities of their journey and confront the ultimate truth of their existence.

In the face of uncertainty and adversity, the Traveller quest for meaning and connection drives them forward, propelling them towards the centre of the galaxy and the answers that await. Through their odyssey, the Traveller embodies resilience, curiosity, and the enduring spirit of exploration, forging their path amidst the boundless expanse of the cosmos.', 2, 'no-mans-sky', 'Hello Games', '2016-08-09', 59.99),
('Persona 5 Royal', 'The story of "Persona 5" is a gripping tale of redemption, rebellion, and uncovering the truth amidst a web of corruption and deceit. Set against the backdrop of modern-day Tokyo, the protagonist, known as Joker, finds himself thrust into a world of supernatural powers and moral ambiguity after being framed for a crime he didnt commit.

As Joker navigates the treacherous landscape of Shujin Academy and the Metaverse, he forms bonds with a diverse cast of characters, each grappling with their own personal demons and desires for justice. Together, they form the Phantom Thieves of Hearts, a group dedicated to using their newfound abilities to reform society by targeting the corrupt and twisted hearts of adults.

Through their daring heists in the Metaverse, the Phantom Thieves confront a series of antagonists, each representing a different facet of societal injustice and moral decay. From abusive authority figures like Suguru Kamoshida to manipulative criminals like Junya Kaneshiro and Masayoshi Shido, the Phantom Thieves challenge the status quo and seek to bring about meaningful change.

However, their journey is fraught with peril and betrayal, as they grapple with the consequences of their actions and the revelation of hidden truths. Betrayed by their own ally, Goro Akechi, and hunted by the authorities, the Phantom Thieves must navigate a dangerous game of cat and mouse to uncover the true mastermind behind the conspiracy and bring them to justice.

Ultimately, "Persona 5" is a story of resilience and determination in the face of adversity. Through their bonds of friendship and unwavering resolve, the Phantom Thieves defy the odds and stand up against corruption, proving that even in the darkest of times, hope and justice can prevail.', 3, 'persona-5-royal', 'Atlus', '2020-03-31', 59.99),
('Sea of Thieves', 'Sea of Thieves is a first-person perspective action-adventure game. At the beginning of the game, the player selects their procedurally generated player avatar. The game is set in a shared world, which means groups of players will encounter each other throughout their adventures. Solo and duo players sail around in a nimble sloop while players playing in a group control a larger three-person brigantine or a four-person galleon cooperatively by assuming different roles, such as steering the ship, manning the cannons, navigating, boarding enemy ships, and scouting from the crow nest. Players can save the loadout of the ship and customize the ship hull, figurehead, sails and captain quarters, as well as name their ship. Occasionally players may encounter hostile players who may attack them with cannonballs or board their ship. If areas under the deck take damage, water will flow in and cause the ship to gradually sink. Players need to patch up the holes with planks of wood and bail out water using buckets. Alliances can be established with other player crews. When a treasure item is sold by a member of an alliance, all other members receive gold and reputation points at half of the item normal value. Ships in an alliance fly the same flag and are visible on the map tables on other ships in the alliance. Forming an alliance does not prevent players from attacking each other. If a player dies, there is a limited window of time during which they are able to be revived by crewmates or allied player crews. If they are not revived in time, they are sent to a ghost ship known as the Ferry of the Damned where they wait until they can respawn on their crew ship. A competitive multiplayer mode named "Arena" was introduced in the Anniversary update, allowing up to six teams of players to compete against each other by gathering silver in smaller maps. Due to low player participation, this game mode was subsequently removed in a later update. A player-versus-environment mode named "Safer Seas" was introduced in December 2023.', 2, 'sea-of-thieves', 'Rare', '2018-03-20', 39.99),
('Senua''s Saga: Hellblade II', 'Senua Saga: Hellblade II is a third-person action-adventure game. It carries over the concepts and gameplay elements of its predecessor, including permadeath, utilizing puzzles and runes to advance, and an examination of Senua mental state. A new fighting system, more dynamic and realistic than the previous one, will also be included in the game. Along with Senua own background and connections, the game will go deeper into the Norse mythology and history that served as inspiration for the narrative.

Combat designer Juan Fernández explained that Ninja Theory is raising the bar with respect to Hellblade II combat. Juan Fernández pointed out that fewer than 20 people worked on the previous game development, and Ninja Theory has increased its production efforts for the follow-up. As a result, there is going to be more complex combat and a wider variety of opponents in Hellblade II.', 2, 'Senua-sSagaHellbladeII', 'Ninja Theory', '2024-06-06', 59.99),
('The Callisto Protocol', 'Here the modified text without the [number]:

In 2320, Jacob Lee and Max Barrow are contract freight transporters working for the United Jupiter Company (UJC). The two decide to retire after ferrying one last shipment between Europa and the UJC-operated Black Iron Prison on Callisto. Shortly after leaving Black Iron in their ship, the Charon, they are boarded by the Outer Way, a terrorist group purportedly responsible for a massive biological attack on Europa, and the ship crash-lands back on Callisto. Max is killed, leaving Jacob and Outer Way leader Dani Nakamura as the only survivors. They are recovered by Black Iron Prison security head Captain Leon Ferris and incarcerated on the orders of Warden Duncan Cole. After an intake process, Jacob awakens to find the prison overrun by hostile "biophages", inmates afflicted with an unknown disease. He encounters Elias Porter, a prisoner who claims to have an escape plan. After freeing Elias, Jacob fights and leaves Ferris to die at the hands of biophages.

Elias convinces Jacob to locate a hacker in the Special Housing Unit to summon a ship for their escape. The hacker is revealed to be Dani, but she refuses to join them. On their way to the hangar, Jacob and Elias are intercepted by a partially-infected Ferris and are ejected onto Callisto surface; Elias suffers fatal injuries in the process. Dani appears in a half-track and recovers Elias memories of Black Iron and decides to assist Jacob as the biophages mutate and become more dangerous. After Dani fails to find evidence of the UJC illegally smuggling bioweapons in the wreckage of Charon, the two make it to the hangar where they summon a ship. Cole intervenes and shoots down the ship, causing it to crash into and destroy the hangar.

With their method of escape gone, Jacob and Dani decide to confront Cole. The two make their way through the ruins of Arcas, Callisto original colony before it was abandoned and the Black Iron Prison built over it. They find a lab holding a dead creature that the original Arcas miners unearthed, and learn the biophages originated from larvae that were found in the creature. Seeing its potential for accelerating evolution, the UJC harvested the creature larvae and began experimenting with it on humans, causing an outbreak in Arcas; one biophage, Subject Zero, retained his intelligence before the UJC destroyed the colony. After Jacob and Dani fend off an encounter with Ferris, Dani becomes infected. Returning to Black Iron, Jacob is knocked out by a security robot and imprisoned.', 1, 'TheCallistoProtocol', 'Striking Distance Studios', '2022-12-02', 59.99),
('Watch Dogs: Legion', 'The storyline of "Watch Dogs: Legion" is a thrilling narrative of resistance against tyranny and oppression in a near-future London controlled by corrupt authorities and powerful criminal syndicates. It begins with a devastating attack on the Houses of Parliament by a rogue hacker group called "Zero Day," which sets off a chain of events leading to the rise of an authoritarian regime in the city.

As the government enlists private military company Albion to restore order and hunt down members of the hacker group DedSec, citizens find themselves living in a surveillance state where personal freedoms are severely restricted. However, amidst the chaos, DedSec refuses to be silenced and begins a campaign to liberate London from the grip of its oppressors.

Led by the resourceful Sabine Brandt and their AI companion Bagley, DedSec recruits ordinary citizens to join their cause and fight back against Albion and other nefarious forces. Together, they work to expose the truth behind the bombings and unravel the web of corruption and conspiracy that threatens to engulf the city.

As the story unfolds, DedSec uncovers shocking revelations about the involvement of powerful figures like Albion CEO Nigel Cass and criminal organization Clan Kelley in the attacks. They also uncover the sinister experiments of technology company Broca Tech and the internal power struggles within SIRS, the conglomerate of Britain intelligence agencies.

Despite facing numerous obstacles and betrayals, DedSec remains undeterred in their mission to restore freedom and justice to London. With courage, determination, and the support of the city inhabitants, they strive to dismantle the oppressive regime and bring those responsible for the chaos to justice.

"Watch Dogs: Legion" is a captivating tale of resistance, redemption, and the power of ordinary people to change the course of history in the face of overwhelming odds.', 2, 'watch-dogs-legion', 'Ubisoft', '2020-10-29', 59.99),
('Yakuza: Like a Dragon', 'In 2001, Masumi Arakawa persuades Ichiban Kasuga to confess to a murder that his captain, Jo Sawashiro, allegedly committed, to protect the latter reputation. Kasuga, feeling indebted to Arakawa, agrees to shoulder the blame for the crime. Arakawa promises to greet Kasuga upon his release. 18 years later, after serving his sentencing, Kasuga is released from jail, but Arakawa is nowhere to be seen. He is picked up by police officer Koichi Adachi, who reveals that the Tojo Clan has perished, and in its place, Kamurocho has become the territory of its rival, the Omi Alliance. Adachi also informs Kasuga that Arakawa was responsible as he betrayed the clan to join the Omi, while Arakawa son Masato, whom Kasuga once chauffeured, has died due to his deteriorating health. Seeking to expose the truth together, they crash an Omi Alliance meeting held by Arakawa. Adachi is arrested for trespassing whilst Arakawa shoots Kasuga.

Three days later, a homeless man named Yu Nanba heals Kasuga wounds after discovering his body in Isezaki Ijincho. Nanba sees a counterfeit bill in Kasuga pocket and tells him that he is safe from the Omi Alliance because Ijincho is hostile territory. Kasuga and Nanba meet Adachi, where they agree to work for soapland owner Isao Nonomiya to make extra money. After uncovering a conspiracy plot at the city retirement home, the gang discovers that Nonomiya is murdered, which alerts Saeko Mukoda, one of his employees. Determined to find Nonomiya murderer, Saeko joins Kasuga team. The party discovers that his killer is Akira Mabuchi, a lieutenant of the Yokohama Liumang. They also uncover the Liumang collaboration with the Geomijul Mafia and Seiryu Clan in running a money counterfeiting scheme. This money is used by Yutaka Ogikubo, a high-profile politician, to bribe the local police into effectively preserving peace.

The Liumang catch the group investigating the scheme and turns them over to Mabuchi. Mabuchi reveals that he deliberately engineered the prior events so that he could frame the party as warmongering Seiryu Clan members. Joongi Han, the second-in-command of the Geomijul, saves the party from Mabuchi. Mabuchi nonetheless executes two Seiryu Clan members to provoke further retaliation. Kasuga party heads to the Geomijul HQ so that they can find proof of Mabuchi guilt and convince the other Ijincho gangs to not war against each other. Seonhee, the leader of Geomijul, reveals to everyone that Nanba pretended to be homeless so that he could investigate his brother disappearance after the latter tried to expose the money counterfeiting scheme. She rallies the Geomijul and the Liumang into executing Nanba, prompting him to seek refuge in the HQ of Bleach Japan, co-founded by Tokyo governor Ryo Aoki. Kasuga eventually deduces that Aoki is Masato, who took on a new identity and used Bleach Japan to cleanse Kamurocho of the Tojo Clan influence. However, as the police were afraid of a power vacuum, Aoki ordered the Omi Alliance to take over Kamurocho with Arakawa help. Aoki seeks to win the support of Ijincho by undermining the Yokohama underworld by bribing Mabuchi into provoking a civil war.', 3, 'YakuzaLikeaDragon', 'Ryu Ga Gotoku Studio', '2020-11-10', 59.99),
('Dragon''s Dogma 2', 'Dragon Dogma 2 is an action role-playing game played from a third-person perspective. The player takes on the role of a character called the "Arisen", a hero marked by a dragon whom they must defeat. The player explores the world they live in, taking on quests, and fighting monsters, while being caught up in a geopolitical conflict between two kingdoms. To assist in this, the Arisen relies on allies called "Pawns", non-playable characters who join the player party. These characters are AI-controlled, but function like player-controlled avatars, able to assist in fights, provide information on enemies, and give guidance to active quests. Players can each create and customize their avatar and their own Pawn character with different genders, appearances, and race. In addition, players can recruit two additional Pawns that have been created by other players.

Both the Arisen and Pawns each operate under a "vocation" – a class that defines what abilities and equipment they can use in combat, with different strengths and weaknesses. Vocations are split between basic, advanced and hybrid, the latter only accessible to the Arisen; furthermore, only the Arisen and their Pawn can change vocations. The game features several different vocations to choose from; several from Dragon Dogma make a return, whilst Strider and Ranger have been changed to Thief and Archer respectively. New hybrid vocations are included, including Mystic Spearhand, a variation of Mystic Knight, with characters able to utilize a bladed quarterstaff-like weapon called a duospear, and the Trickster, who uses spells that can confuse enemies and enhance Pawns in battle. Working with vocations improves them, unlocking additional abilities that can be acquired for use in combat.', 3, 'dragons-dogma2', 'Capcom', '2024-03-21', 59.99);







